# Generated by Django 4.2.24 on 2025-09-24 01:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0008_alter_sheetmusic_file_alter_theme_audio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del lugar')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('country', models.CharField(default='Argentina', max_length=100, verbose_name='País')),
                ('capacity', models.PositiveIntegerField(help_text='Capacidad máxima de personas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del repertorio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Repertorio',
                'verbose_name_plural': 'Repertorios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepertoireVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de la versión en el repertorio')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.repertoire')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.version')),
            ],
            options={
                'verbose_name': 'Versión en repertorio',
                'verbose_name_plural': 'Versiones en repertorios',
                'ordering': ['order', 'created_at'],
                'unique_together': {('repertoire', 'version')},
            },
        ),
        migrations.AddField(
            model_name='repertoire',
            name='versions',
            field=models.ManyToManyField(blank=True, related_name='repertoires', through='events.RepertoireVersion', to='music.version', verbose_name='Versiones de temas'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del evento')),
                ('event_type', models.CharField(choices=[('CONCERT', 'Concierto'), ('REHEARSAL', 'Ensayo'), ('RECORDING', 'Grabación'), ('WORKSHOP', 'Taller'), ('OTHER', 'Otro')], default='CONCERT', max_length=20, verbose_name='Tipo de evento')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado'), ('COMPLETED', 'Completado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_datetime', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fecha y hora de finalización')),
                ('is_public', models.BooleanField(default=False, verbose_name='Evento público')),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='Dejar en blanco para usar la capacidad del lugar', null=True, verbose_name='Máximo de asistentes')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='0 para entrada gratuita', max_digits=10, verbose_name='Precio de entrada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.location', verbose_name='Ubicación')),
                ('repertoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.repertoire', verbose_name='Repertorio')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_datetime'],
            },
        ),
    ]
