# Generated by Django 5.2.6 on 2025-11-04 13:31

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs_for_existing_events(apps, schema_editor):
    """
    Genera slugs únicos para todos los eventos existentes.
    """
    Event = apps.get_model('events', 'Event')

    for event in Event.objects.all():
        if not event.title:
            continue

        # Generar slug base
        base_slug = slugify(event.title)[:50]
        slug = base_slug
        counter = 1

        # Encontrar slug único
        while Event.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
            if len(slug) > 100:
                base_slug = base_slug[:50 - len(str(counter)) - 1]
                slug = f"{base_slug}-{counter}"

        event.slug = slug
        event.save(update_fields=['slug'])


def reverse_generate_slugs(apps, schema_editor):
    """
    Función reversa (opcional, podría dejar slugs en blanco)
    """
    Event = apps.get_model('events', 'Event')
    Event.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        # Paso 1: Agregar campo slug sin unique y sin blank
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(
                default='',
                max_length=100,
                verbose_name='Slug',
                help_text='URL amigable generada automáticamente desde el título'
            ),
            preserve_default=False,
        ),
        # Paso 2: Generar slugs para eventos existentes
        migrations.RunPython(
            generate_slugs_for_existing_events,
            reverse_generate_slugs
        ),
        # Paso 3: Modificar campo para agregar unique y blank
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(
                blank=True,
                max_length=100,
                unique=True,
                verbose_name='Slug',
                help_text='URL amigable generada automáticamente desde el título'
            ),
        ),
    ]
