# Generated by Django 5.2.6 on 2025-11-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='google_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Google Maps'),
        ),
    ]
