# Generated by Django 5.2.6 on 2025-11-12 00:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target', models.IntegerField(help_text='Meta a alcanzar', validators=[django.core.validators.MinValueValidator(1)])),
                ('metric_type', models.CharField(choices=[('lessons_completed', 'Lecciones Completadas'), ('exercises_completed', 'Ejercicios Completados'), ('streak_days', 'Días de Racha'), ('perfect_lessons', 'Lecciones Perfectas (3 estrellas)'), ('total_xp', 'XP Total')], max_length=50)),
                ('xp_reward', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji', max_length=10)),
                ('category', models.CharField(choices=[('beginner', 'Principiante'), ('progress', 'Progreso'), ('mastery', 'Maestría'), ('streak', 'Racha'), ('special', 'Especial')], max_length=50)),
                ('unlock_criteria', models.JSONField(help_text='\n        Ejemplo: {\n            "type": "lessons_completed",\n            "target": 5\n        }\n        ')),
                ('xp_reward', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insignia',
                'verbose_name_plural': 'Insignias',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji o código de ícono', max_length=10)),
                ('color', models.CharField(default='#1CB0F6', help_text='HEX color', max_length=7)),
                ('category', models.CharField(choices=[('notes', 'Notas'), ('rhythm', 'Ritmo'), ('theory', 'Teoría'), ('chords', 'Acordes'), ('intervals', 'Intervalos')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=20)),
                ('estimated_time', models.IntegerField(help_text='Tiempo estimado en minutos', validators=[django.core.validators.MinValueValidator(1)])),
                ('xp_reward', models.IntegerField(default=50, help_text='XP base por completar', validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.IntegerField(default=0, help_text='Orden en el path de aprendizaje')),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_created', to=settings.AUTH_USER_MODEL)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='music_learning.lesson')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('note-recognition', 'Reconocimiento de Notas'), ('rhythm', 'Ritmo'), ('chord', 'Acordes'), ('interval', 'Intervalos'), ('theory', 'Teoría Musical')], max_length=50)),
                ('question', models.TextField(help_text='Pregunta del ejercicio')),
                ('hint', models.TextField(blank=True, help_text='Pista opcional')),
                ('options', models.JSONField(help_text="Array de opciones: ['Do', 'Re', 'Mi', 'Fa']")),
                ('correct_answer', models.JSONField(help_text='Respuesta correcta (string o array para múltiples)')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], max_length=20)),
                ('xp_reward', models.IntegerField(default=10, help_text='XP por respuesta correcta', validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='music_learning.lesson')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('stars', models.IntegerField(default=0, help_text='0-3 estrellas', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('best_score', models.IntegerField(default=0, help_text='Mejor puntaje obtenido', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attempts', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('first_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='music_learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Lección',
                'verbose_name_plural': 'Progresos de Lecciones',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.JSONField(help_text='Respuesta del usuario')),
                ('is_correct', models.BooleanField()),
                ('time_spent', models.IntegerField(help_text='Segundos que tomó responder', validators=[django.core.validators.MinValueValidator(0)])),
                ('xp_earned', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='music_learning.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL)),
                ('lesson_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to='music_learning.lessonprogress')),
            ],
            options={
                'verbose_name': 'Intento de Ejercicio',
                'verbose_name_plural': 'Intentos de Ejercicios',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='music_learning.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='music_learning.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insignia de Usuario',
                'verbose_name_plural': 'Insignias de Usuarios',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('current_xp', models.IntegerField(default=0, help_text='XP en el nivel actual', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_xp', models.IntegerField(default=0, help_text='XP acumulado total', validators=[django.core.validators.MinValueValidator(0)])),
                ('current_streak', models.IntegerField(default=0, help_text='Días consecutivos', validators=[django.core.validators.MinValueValidator(0)])),
                ('longest_streak', models.IntegerField(default=0, help_text='Mejor racha', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_practice_date', models.DateField(blank=True, null=True)),
                ('total_lessons_completed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_exercises_completed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_practice_time', models.IntegerField(default=0, help_text='Minutos totales', validators=[django.core.validators.MinValueValidator(0)])),
                ('correct_answers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_answers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sound_enabled', models.BooleanField(default=True)),
                ('music_enabled', models.BooleanField(default=True)),
                ('vibration_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['slug'], name='music_learn_slug_bf8269_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['category', 'difficulty'], name='music_learn_categor_595326_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_published', 'order'], name='music_learn_is_publ_db5a17_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['lesson', 'order'], name='music_learn_lesson__5a9525_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'lesson'], name='music_learn_user_id_b66ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['is_completed', 'updated_at'], name='music_learn_is_comp_3f3a63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['user', 'attempted_at'], name='music_learn_user_id_6b4a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['exercise', 'is_correct'], name='music_learn_exercis_bf5e81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
    ]
