# Generated by Django 4.2.27 on 2025-12-03 04:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('note-holding', 'Sostener Nota'), ('pitch-matching', 'Igualar Tono'), ('rhythm-clapping', 'Palmear Ritmo')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=20)),
                ('xp_reward', models.IntegerField(default=50, help_text='XP base por completar', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Desafío',
                'verbose_name_plural': 'Desafíos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('note-recognition', 'Reconocimiento de Notas'), ('rhythm', 'Ritmo'), ('chord', 'Acordes'), ('interval', 'Intervalos'), ('theory', 'Teoría Musical'), ('note-holding', 'Sostener Nota')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('stars', models.IntegerField(default=0, help_text='0-3 estrellas basado en accuracy', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('accuracy', models.FloatField(default=0.0, help_text='Porcentaje de precisión (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('best_accuracy', models.FloatField(default=0.0, help_text='Mejor accuracy alcanzado', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attempts', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_xp_earned', models.IntegerField(default=0, help_text='XP total ganado en este desafío', validators=[django.core.validators.MinValueValidator(0)])),
                ('first_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='music_learning.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Desafío',
                'verbose_name_plural': 'Progresos de Desafíos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(help_text='Nota musical: C, D, E, F, G, A, B', max_length=2)),
                ('octave', models.IntegerField(help_text='Octava: 3, 4, 5, etc.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('beats_to_hold', models.IntegerField(help_text='Cantidad de beats a sostener', validators=[django.core.validators.MinValueValidator(1)])),
                ('bpm', models.IntegerField(default=60, help_text='Tempo del metrónomo (beats por minuto)', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(240)])),
                ('cents_threshold', models.IntegerField(default=15, help_text='Margen de error en cents (±)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('order', models.IntegerField(default=0, help_text='Orden de la nota en la secuencia')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='music_learning.challenge')),
            ],
            options={
                'verbose_name': 'Nota de Desafío',
                'verbose_name_plural': 'Notas de Desafío',
                'ordering': ['challenge', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['slug'], name='music_learn_slug_65af9c_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['type', 'difficulty'], name='music_learn_type_dcb2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallengeprogress',
            index=models.Index(fields=['user', 'challenge'], name='music_learn_user_id_a798d7_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallengeprogress',
            index=models.Index(fields=['is_completed', 'updated_at'], name='music_learn_is_comp_0bd62f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userchallengeprogress',
            unique_together={('user', 'challenge')},
        ),
        migrations.AddIndex(
            model_name='challengenote',
            index=models.Index(fields=['challenge', 'order'], name='music_learn_challen_d59ac7_idx'),
        ),
    ]
