# Generated by Django 5.2.6 on 2025-09-19 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='instrument',
            name='afinacion',
            field=models.CharField(blank=True, choices=[('Bb', 'Si bemol'), ('Eb', 'Mi bemol'), ('F', 'Fa'), ('C', 'Do'), ('G', 'Sol'), ('D', 'Re'), ('A', 'La'), ('E', 'Mi'), ('NONE', 'Sin afinación específica')], max_length=10),
        ),
        migrations.AddField(
            model_name='theme',
            name='tonalidad',
            field=models.CharField(blank=True, choices=[('C', 'Do Mayor'), ('Cm', 'Do menor'), ('C#', 'Do# Mayor'), ('C#m', 'Do# menor'), ('D', 'Re Mayor'), ('Dm', 'Re menor'), ('D#', 'Re# Mayor'), ('D#m', 'Re# menor'), ('E', 'Mi Mayor'), ('Em', 'Mi menor'), ('F', 'Fa Mayor'), ('Fm', 'Fa menor'), ('F#', 'Fa# Mayor'), ('F#m', 'Fa# menor'), ('G', 'Sol Mayor'), ('Gm', 'Sol menor'), ('G#', 'Sol# Mayor'), ('G#m', 'Sol# menor'), ('A', 'La Mayor'), ('Am', 'La menor'), ('A#', 'La# Mayor'), ('A#m', 'La# menor'), ('B', 'Si Mayor'), ('Bm', 'Si menor')], max_length=10),
        ),
        migrations.AddField(
            model_name='version',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='versions/images/'),
        ),
        migrations.RemoveField(
            model_name='version',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='version',
            name='sheet_music',
        ),
        migrations.CreateModel(
            name='SheetMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sheet_music/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_music', to='music.instrument')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_music', to='music.version')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('version', 'instrument')},
            },
        ),
    ]
