# Generated by Django 5.2.6 on 2025-09-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_version_unique_together_instrument_afinacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('ENSAMBLE', 'Ensamble'), ('DUETO', 'Dueto'), ('GRUPO_REDUCIDO', 'Grupo Reducido')], default='STANDARD', max_length=20),
        ),
    ]
