# Generated by Django 5.2.6 on 2025-09-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_version_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sheetmusic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='type',
            field=models.CharField(choices=[('MELODIA_PRINCIPAL', 'Melodía Principal'), ('MELODIA_SECUNDARIA', 'Melodía Secundaria'), ('ARMONIA', 'Armonía'), ('BAJO', 'Bajo')], default='MELODIA_PRINCIPAL', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='sheetmusic',
            unique_together={('version', 'instrument', 'type')},
        ),
    ]
