# Generated by Django 5.2.6 on 2025-09-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_sheetmusic_unique_together_sheetmusic_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='mus_file',
            field=models.FileField(blank=True, help_text='Archivo de MuseScore (.mscz, .mscx)', null=True, upload_to='versions/musescore/'),
        ),
    ]
