# Generated by Django 5.2.6 on 2025-09-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_version_mus_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmusic',
            name='clef',
            field=models.CharField(choices=[('SOL', 'Clave de Sol'), ('FA', 'Clave de Fa')], default='SOL', max_length=10),
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='tonalidad_relativa',
            field=models.CharField(blank=True, help_text='Tonalidad calculada según la afinación del instrumento', max_length=10),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='family',
            field=models.CharField(blank=True, choices=[('VIENTO_MADERA', 'Vientos-Madera'), ('VIENTO_METAL', 'Vientos-Metales'), ('PERCUSION', 'Percusión')], max_length=20),
        ),
    ]
