# Generated by Django 5.2.6 on 2025-09-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_sheetmusic_clef_sheetmusic_tonalidad_relativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='artist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='theme',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='themes/audio/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='themes/images/'),
        ),
    ]
