# Generated by Django 4.2.24 on 2025-09-24 01:51

from django.db import migrations, models
import music.utils


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_theme_artist_theme_audio_theme_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmusic',
            name='file',
            field=models.FileField(upload_to=music.utils.sheet_music_upload_path),
        ),
        migrations.AlterField(
            model_name='theme',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=music.utils.theme_audio_upload_path),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=music.utils.theme_image_upload_path),
        ),
        migrations.AlterField(
            model_name='version',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=music.utils.version_audio_upload_path),
        ),
        migrations.AlterField(
            model_name='version',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=music.utils.version_image_upload_path),
        ),
        migrations.AlterField(
            model_name='version',
            name='mus_file',
            field=models.FileField(blank=True, help_text='Archivo de MuseScore (.mscz, .mscx)', null=True, upload_to=music.utils.version_mus_file_upload_path),
        ),
    ]
