# Generated by Django 4.2.25 on 2025-11-06 04:15

from django.db import migrations, models
import django.db.models.deletion
import music.utils


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_sheetmusic_file_alter_theme_audio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('DUETO_TRANSPOSITION', 'Dueto - Transposición'), ('ENSAMBLE_INSTRUMENT', 'Ensamble - Instrumento'), ('STANDARD_SCORE', 'Standard - Partitura General')], help_text='Tipo de archivo según el tipo de version', max_length=30)),
                ('tuning', models.CharField(blank=True, choices=[('Bb', 'Si bemol - Clave de Sol'), ('Eb', 'Mi bemol - Clave de Sol'), ('F', 'Fa - Clave de Sol'), ('C', 'Do - Clave de Sol'), ('C_BASS', 'Do - Clave de Fa (Bass)')], help_text='Afinación/transposición del archivo (solo para DUETO)', max_length=10, null=True)),
                ('file', models.FileField(help_text='Archivo PDF de la partitura', upload_to=music.utils.version_file_upload_path)),
                ('audio', models.FileField(blank=True, help_text='Archivo de audio opcional para esta versión', null=True, upload_to=music.utils.version_file_audio_upload_path)),
                ('description', models.TextField(blank=True, help_text='Descripción o notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(blank=True, help_text='Instrumento específico (solo para ENSAMBLE)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_files', to='music.instrument')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_files', to='music.version')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='versionfile',
            constraint=models.UniqueConstraint(condition=models.Q(('file_type', 'DUETO_TRANSPOSITION')), fields=('version', 'tuning'), name='unique_version_dueto_tuning'),
        ),
        migrations.AddConstraint(
            model_name='versionfile',
            constraint=models.UniqueConstraint(condition=models.Q(('file_type', 'ENSAMBLE_INSTRUMENT')), fields=('version', 'instrument'), name='unique_version_ensamble_instrument'),
        ),
    ]
